import { OpenAI } from 'openai';
import { OPENAI_API_KEY } from '@env';

const openai = new OpenAI({
  apiKey: OPENAI_API_KEY,
});


console.log(`openai: ${OPENAI_API_KEY}`);

export const generateInvoice = async ({
  projectName,
  projectDescription,
  clientName,
  clientEmail,
  freelancerEmail,
  hourlyRate,
  totalTime,
  task_name,
  dueDate,
}: {
  projectName: string;
  projectDescription: string;
  clientName: string;
  clientEmail: string;
  freelancerEmail: string;
  hourlyRate: number;
  totalTime: number;
  dueDate: string;
  task_name: string;
}) => {
  const prompt = `
Act as a professional invoice generator for a freelancing platform called "Microtasker." Generate a complete HTML document for a highly professional, clean, and structured invoice, mimicking the style of invoices from major e-commerce platforms like Amazon or Flipkart. The invoice should have a polished layout with clearly defined sections, professional formatting, and a modern design aesthetic with a subtle background (e.g., a light gradient or watermark). Use Tailwind CSS (via CDN: https://cdn.tailwindcss.com) for styling.

**Invoice Details:**
- Invoice Issued by: Microtasker
- Invoice Date: July 28, 2025
- Invoice Due Date: ${dueDate}

**Client Details:**
- Client Name: ${clientName}
- Client Email: ${clientEmail}

**Freelancer Details:**
- Freelancer Email: ${freelancerEmail}

**Project Details:**
- Project Name: ${projectName}
- Project Description: ${projectDescription}
- Task Name: ${task_name}

**Billing Details:**
- Hourly Rate: $${hourlyRate.toFixed(2)}
- Total Time Taken: ${totalTime} hours
- Total Bill: $${(hourlyRate * totalTime).toFixed(2)}

**Requirements:**
1. Generate a complete HTML document with <!DOCTYPE html>, <html>, <head>, and <body>.
2. Include Tailwind CSS via CDN in the <head>.
3. Structure the invoice with sections: Header (with Microtasker branding), Client Details, Freelancer Details, Project Details, Billing Summary (as a table), Payment Instructions, and Footer.
4. Use a Tailwind-styled table for the billing summary with columns: Description, Quantity, Rate, Amount.
5. Apply a professional background (e.g., linear-gradient or subtle watermark with "Microtasker").
6. Ensure proper alignment (e.g., left-aligned labels, right-aligned values).
7. Add a header with "Microtasker Invoice" in bold, modern font.
8. Include payment instructions: "Please remit payment to payments@microtasker.com via bank transfer or PayPal by the due date."
9. Add a polite closing note thanking the client and expressing interest in future collaborations.
10. Include a footer: "Generated by Microtasker | support@microtasker.com".
11. Escape special HTML characters (e.g., &, <, >) in the provided details to avoid rendering issues.
12. Use Tailwind classes for a clean, professional look (e.g., bg-gradient-to-r, shadow-md, rounded-lg).

**Output:**
Return only the complete HTML code as plain text, starting with <!DOCTYPE html> and ending with </html>. Do not include any explanations or non-HTML content.
`;

  const response = await openai.chat.completions.create({
    model: 'gpt-4',
    messages: [{ role: 'user', content: prompt }],
    temperature: 0.7,
  });

  return response.choices[0].message?.content || '';
};