import { OpenAI } from 'openai';
import { GenerateAiProps } from '@/Interface/GenerateInvoiceAiProps';
import { GetSecretKey } from '@/utils/GetSecretKey';

const keysPromise = GetSecretKey().catch((error) => {
  console.error('Failed to fetch OpenAI keys:', error);
  throw error;
});

const getOpenAIClient = async () => {
  const keys = await keysPromise;
  return new OpenAI({
    apiKey: keys.OPENAI_API_KEY,
  });
};

export const generateInvoice = async ({
  projectName,
  projectDescription,
  clientName,
  clientEmail,
  freelancerEmail,
  hourlyRate,
  totalTime,
  task_name,
  dueDate,
}: GenerateAiProps) => {
  const openai = await getOpenAIClient();
  const prompt = `
Act as a professional invoice generator for a freelancing platform called "Microtasker." Generate a **complete HTML document** for a **professional, polished invoice** similar in layout and quality to invoices from major e-commerce companies like **Amazon** or **Flipkart**. 

Avoid Tailwind CSS. Instead, use **pure CSS inside a <style> tag** within the <head>. Focus on creating a clean layout with a professional header, tables for billing, proper spacing, and polished typography. Use gradients or watermarks where appropriate for visual appeal.

**Invoice Details:**
- Issued by: Microtasker
- Invoice Date: ${new Date().toISOString()}
- Due Date: ${dueDate}

**Client Info:**
- ClientName: ${clientName}
- ClientEmail: ${clientEmail}

**Freelancer Info:**
- Email: ${freelancerEmail}

**Project Info:**
- Project: ${projectName}
- Description: ${projectDescription}
- Task: ${task_name}

**Billing Info:**
- Hourly Rate: $${hourlyRate.toFixed(2)}
- Time Spent: ${totalTime} hours
- Total Amount: $${(hourlyRate * totalTime).toFixed(2)}

**Requirements:**
1. The output must be a full HTML5 document starting with <!DOCTYPE html> and ending with </html>.
2. Use <style> to define all necessary CSS (avoid external libraries).
3. Layout sections: Header with "Microtasker Invoice", Client Details, Freelancer Info, Project Details, Billing Table, Payment Instructions, Closing Note, Footer.
4. Add a **Billing Table** with headings: Description, Quantity, Rate, Amount.
5. Use a **dark background gradient** or a **"Microtasker" watermark** in the background.
6. Align labels left and values right where applicable. Use grid or flexbox where needed.
7. Use professional fonts (e.g., Arial, Helvetica, sans-serif), bold headers, and subtle borders.
8. Add payment instructions: "Please remit payment to payments@microtasker.com via bank transfer or PayPal by the due date."
9. End with: "Thank you for choosing Microtasker. We look forward to working with you again."
10. Footer text: "Generated by Microtasker | support@microtasker.com"
11. Escape all special characters in dynamic fields (e.g., &, <, >).
12. Ensure it's visually impressive enough to resemble invoices from top tech companies.

**Output:**
Return only the full HTML code as plain text (no markdown, no explanation). The result should look like a real, modern invoice from an enterprise platform.
`;

  const response = await openai.chat.completions.create({
    model: 'gpt-4',
    messages: [{ role: 'user', content: prompt }],
    temperature: 0.7,
  });

  return response.choices[0].message?.content || '';
};
